import { Background } from "@/components/background";
import Header from "@/components/header";
import "@/styles/global.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Background />
        <Header />
        {children}
      </body>
    </html>
  );
}
